DOFArray: Pickle/unpickle tags
inducer/meshmode pull request #318
Opened 2022-04-03 20:23 UTC by matthiasdiener

Potential fix for #317

2022-04-03 20:37 UTC, inducer reviewed
Thanks! This makes sense. Some comments below.

2022-04-03 20:37 UTC, inducer commented on meshmode/dof_array.py
> +        tags = state[1]
```suggestion
        data, tags = state
```

2022-04-03 20:37 UTC, inducer commented on meshmode/dof_array.py
> +        data = state[0]
Unless we make this backward-compatible, this will needlessly break existing restart files. (But do include a warning.)

2022-04-03 20:38 UTC, inducer commented
> A test might be necessary

Agree

2022-04-03 20:39 UTC, kaushikcfd requested changes
Thanks, left some questions to discuss. This also needs some tests.

2022-04-03 20:39 UTC, kaushikcfd commented on meshmode/dof_array.py
> +            [ary_i.tags for ary_i in ary._data])
1. We should probably store this as a dict?
2. Also needs `.axes` metadata.
3. What about some array contexts that operate on arrays that do not have `.tags` attribute?
4. Should we care about backward compatibility with the existing data that was pickled before this PR?

2022-04-04 00:37 UTC, matthiasdiener commented on meshmode/dof_array.py
> +        tags = state[1]
Updated by [cfa2262](https://github.com/inducer/meshmode/pull/318/commits/cfa226289c43c89b278e03a988aaad8f8599a2ad)

2022-04-04 00:37 UTC, matthiasdiener commented on meshmode/dof_array.py
> +        data = state[0]
I *think* [cfa2262](https://github.com/inducer/meshmode/pull/318/commits/cfa226289c43c89b278e03a988aaad8f8599a2ad), but haven't tested yet.

2022-04-04 00:42 UTC, matthiasdiener commented on meshmode/dof_array.py
> +            [ary_i.tags for ary_i in ary._data])
> 1. We should probably store this as a dict?
Done in https://github.com/inducer/meshmode/pull/318/commits/2283819975aa5b0fdbc38e1abaf987aafc6e84e8
> 2. Also needs `.axes` metadata.
Done in https://github.com/inducer/meshmode/pull/318/commits/de6e398d5d8b4605a3a3dc5b8d870be3e514d418
> 3. What about some array contexts that operate on arrays that do not have `.tags` attribute?
https://github.com/inducer/meshmode/pull/318/commits/17e63d660cb4e0ccb23e9ecb4b3242aa108efcbb should hopefully fix that
> 4. Should we care about backward compatibility with the existing data that was pickled before this PR?

See [cfa2262](https://github.com/inducer/meshmode/pull/318/commits/cfa226289c43c89b278e03a988aaad8f8599a2ad)

2022-04-04 00:49 UTC, matthiasdiener commented
This is ready for a second look. There are some strange CI errors that are probably unrelated to this PR.

2022-04-04 01:39 UTC, inducer commented
> There are some strange CI errors that are probably unrelated to this PR.

Those were my fault. I screwed something up in ci-support.

2022-04-04 03:51 UTC, kaushikcfd approved these changes
Thanks! Suggested some minor changes, otherwise LGTM.

2022-04-04 03:51 UTC, kaushikcfd commented on meshmode/dof_array.py
> +        d["axes_tags"] = [ax.tags for ary_i in ary._data for ax in ary_i.axes]
1. Another `hasattr(..., "axes")` here?
2. A more natural way to store it is a list of list? The inner list stores the tags corresponding to each axis of the array.

2022-04-04 17:53 UTC, matthiasdiener commented on meshmode/dof_array.py
> +        d["axes_tags"] = [ax.tags for ary_i in ary._data for ax in ary_i.axes]
Is 
89d7c19 what you had in mind?

2022-04-04 19:30 UTC, kaushikcfd approved these changes
Thanks. Found some minor bugs, and suggested some asserted that would (I think) catch such errors sooner.

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +            d["axes_tags"] = [[] for _ in range(len(ary._data))]
This should be: `d["axes_tags"] = [[frozenset() for _ in range(leaf_ary.ndim)] for leaf_ary in range(len(ary._data))]`

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +            axes_tags = [frozenset() for _ in range(len(state))]
This default is incorrect, according to the implementation in `__getstate__`.

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +
How about an assert here that `assert len(data) == len(tags) == len(axes_tags)`?

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +
How about an assert here that `assert len(axes_tags[idx]) == ary.ndim`?

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +                d = actx.tag_axis(ida, ax, d)
How about an assert before this line that `assert isinstance(axes_tags[idx], frozenset)`?

2022-04-04 19:30 UTC, kaushikcfd commented on meshmode/dof_array.py
> +            d["tags"] = [frozenset() for _ in range(len(ary._data))]
Is it reasonable to expect that `ary._data` has at least 1 array? (I'm not sure, someone else can comment on this?)

2022-04-04 23:38 UTC, matthiasdiener commented on meshmode/dof_array.py
> +
Added in bd439cc159d69b0647375fb4c71f2d3734c227ee, thanks!

2022-04-04 23:38 UTC, matthiasdiener commented on meshmode/dof_array.py
> +
Added in bd439cc159d69b0647375fb4c71f2d3734c227ee, thanks!

2022-04-04 23:38 UTC, matthiasdiener commented on meshmode/dof_array.py
> +                d = actx.tag_axis(ida, ax, d)
`axes_tags[idx]` is a list; added this assert in bd439cc159d69b0647375fb4c71f2d3734c227ee

2022-04-04 23:38 UTC, matthiasdiener commented on meshmode/dof_array.py
> +            d["axes_tags"] = [[] for _ in range(len(ary._data))]
I changed it to `d["axes_tags"] = [[frozenset() for _ in range(leaf_ary.ndim)]
                                         for leaf_ary in ary._data]`

2022-04-04 23:38 UTC, matthiasdiener commented on meshmode/dof_array.py
> +            axes_tags = [frozenset() for _ in range(len(state))]
Thanks, I changed it to `axes_tags = [[frozenset() for _ in range(leaf_ary.ndim)]
                                         for leaf_ary in data]`

2022-04-04 23:50 UTC, matthiasdiener commented on meshmode/dof_array.py
> +            d["tags"] = [frozenset() for _ in range(len(ary._data))]
It seems an empty DOFArray is legal, so I added support for this case in 1ae79bd

2022-04-05 00:03 UTC, alexfikl commented on meshmode/dof_array.py
> +            d["tags"] = [frozenset() for _ in range(len(ary._data))]
```suggestion
	d["tags"] = [getattr(ary_i, "tags", frozenset()) for ary_i in ary]
```
This looks more readable to me and it should catch all the cases. What do you think?

2022-04-05 00:05 UTC, alexfikl commented on meshmode/dof_array.py
> +            d["tags"] = [frozenset() for _ in range(len(ary._data))]
There's probably a similar rewrite for the `axes`, but that's not going to look as nice because of the nesting :\

2022-04-05 01:40 UTC, matthiasdiener commented on meshmode/dof_array.py
> +            d["tags"] = [frozenset() for _ in range(len(ary._data))]
Looks good, thanks!

2022-04-05 04:19 UTC, inducer commented on meshmode/dof_array.py
> +                                         for leaf_ary in data]
Please add a warning here that a `DOFArray` is being unpickled without metadata, and that program transformation may fail as a result.

2022-04-05 06:36 UTC, kaushikcfd commented
The point at which metadata is being recorded may not have everything gone through metadata inference. Needs a freeze, something like this:

```diff
[line@line meshmode]$ git diff
diff --git a/meshmode/dof_array.py b/meshmode/dof_array.py
index eb3cd3f..4375228 100644
--- a/meshmode/dof_array.py
+++ b/meshmode/dof_array.py
@@ -272,7 +272,7 @@ class DOFArray:
             raise RuntimeError("DOFArray instances can only be pickled while "
                     "array_context_for_pickling is active.")
 
-        ary = self
+        ary = _thaw(freeze(self, self.array_context), self.array_context)
 
         if self.array_context is not actx:
             ary = _thaw(actx, _freeze(self))
@@ -286,7 +286,7 @@ class DOFArray:
             d["axes_tags"] = [[ax.tags for ax in ary_i.axes] for ary_i in ary._data]
         else:
             d["axes_tags"] = [[frozenset() for _ in range(leaf_ary.ndim)]
-                                         for leaf_ary in ary._data]
+                              for leaf_ary in ary._data]
 
         return d
```

(We have something similar in arraycontext-land: https://github.com/inducer/arraycontext/pull/152)

2022-04-05 15:36 UTC, inducer commented
> Needs a freeze, something like this:

Also add a comment justifying the thaw/freeze, maybe including a link back to Kaushik's comment.

2022-04-06 00:04 UTC, matthiasdiener commented on meshmode/dof_array.py
> +                                         for leaf_ary in data]
Added in 
137e4dc

2022-04-06 00:05 UTC, matthiasdiener commented
> The point at which metadata is being recorded may not have everything gone through metadata inference. Needs a freeze, something like this:
> 

Added in [0438b18](https://github.com/inducer/meshmode/pull/318/commits/0438b18dc4ac7746f08d72ca1ca740a96398472c)

2022-04-06 06:34 UTC, inducer commented on test/test_array.py
> +def test_dof_array_pickling_tags(actx_factory):
I don't think this test is being run against a lazy array context. I think that would be important to do.

2022-04-07 22:19 UTC, matthiasdiener commented on test/test_array.py
> +def test_dof_array_pickling_tags(actx_factory):
I added testing with pytato to this file in [c82c6c2](https://github.com/inducer/meshmode/pull/318/commits/c82c6c251c36eb31e50839a7e1428814c1439946)

2022-04-17 22:48 UTC, inducer commented
LGTM, thanks!

2022-04-17 22:48 UTC, merged